"""update

Revision ID: 139019174dbc
Revises: 3f2fbddb5fec
Create Date: 2015-12-08 22:19:04.928535

"""

# revision identifiers, used by Alembic.
revision = '139019174dbc'
down_revision = '3f2fbddb5fec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'disabled')
    ### end Alembic commands ###
