"""new

Revision ID: 24f434770d9e
Revises: 48d1edc65ba5
Create Date: 2015-12-04 23:27:19.430606

"""

# revision identifiers, used by Alembic.
revision = '24f434770d9e'
down_revision = '48d1edc65ba5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
