"""update

Revision ID: 48deb381adcc
Revises: 18076d8ef708
Create Date: 2015-12-05 21:15:57.393419

"""

# revision identifiers, used by Alembic.
revision = '48deb381adcc'
down_revision = '18076d8ef708'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
